Repository We-LGD/ddoon-ddoon, pull requests merged in 2024-12, with the labels that each got.

#24 style: 컴포넌트 function 형으로 통일
  src/pages/Loading.tsx
  src/pages/NotFound.tsx
  src/shared/components/atoms/Input.tsx
  src/shared/components/atoms/Title.tsx
  src/shared/components/templates/Layout.tsx
  src/shared/interface/atomsType.ts
Labels: 🪛REFACT

#18 Feature/goose#3 Button 컴포넌트 작업
  src/shared/components/atoms/Button.tsx
  src/shared/interface/atomsType.ts
  src/store/storeType.ts
  src/store/useButtonStore.ts
Labels: ✨FEAT

#16 Feature/goose#4 공통컴포넌트 Slide 작업
  src/shared/components/atoms/Button.tsx
  src/shared/components/atoms/ChellengeAddBtn.tsx
  src/shared/components/atoms/CloseBtn.tsx
  src/shared/components/atoms/Slide.tsx
  src/shared/components/organisms/ChallengeBox.tsx
  src/shared/interface/atomsType.ts
Labels: ✨FEAT

#27 Feature/goose#3 Button 컴포넌트 상태 관리 방식 수정
  src/shared/components/atoms/Button.tsx
  src/shared/interface/atomsType.ts
  src/store/storeType.ts
  src/store/useButtonStore.ts
Labels: 📜DOCU

#26 Feature/Lemon#17 Login 페이지 UI 작업
  src/pages/Login.tsx
Labels: ✨FEAT

#28 Feature/lemon#19 굴이름 정하기 페이지 UI 작업
  src/pages/NicknameSetup.tsx
  src/shared/components/atoms/Button.tsx
  src/shared/components/atoms/Input.tsx
  src/shared/components/templates/Layout.tsx
  src/shared/interface/atomsType.ts
Labels: ✨FEAT

#29 Feature/lemon#21 튜토리얼 페이지 UI 작업
  src/App.tsx
  src/pages/Tutorial.tsx
  src/shared/components/atoms/Slide.tsx
  src/shared/components/templates/Layout.tsx
  src/shared/interface/atomsType.ts
  src/store/storeType.ts
  src/store/useMobileStore.ts
Labels: ✨FEAT

#34 Bug/Lemon#33 모바일 방식 수정
  package.json
  src/pages/Tutorial.tsx
  yarn.lock
Labels: 🐛BUG

#35 Feature/lemon#32 뚠뚠굴 UI 작업
  package.json
  src/App.tsx
  src/index.css
  src/pages/Gool.tsx
  src/pages/Main.tsx
  src/pages/Tutorial.tsx
  src/shared/assets/fonts/Maplestory Light.ttf
  src/shared/assets/fonts/Maplestory OTF Bold.otf
  src/shared/assets/fonts/Maplestory OTF Light.otf
  src/shared/assets/fonts/Maplestory-Bold.ttf
  src/shared/assets/images/100일_구름맵.png
  src/shared/assets/images/30일_구름맵.jpg
  src/shared/assets/images/index.ts
  src/shared/assets/images/뚠뚠굴_3번실패.png
  src/shared/assets/images/뚠뚠굴_8번실패.png
  src/shared/assets/images/뚠뚠굴_배경.png
  src/shared/assets/images/뚠뚠굴_빈굴.png
  src/shared/assets/images/뚠뚠굴_튜토리얼.png
  src/shared/assets/images/뚠뚠굴_팻말.png
  src/shared/assets/images/뚠뚠굴빈굴.png
  src/shared/components/organisms/NavBar.tsx
  src/shared/components/templates/SuccessModal.tsx
  src/shared/components/templates/TutorialRewardModal.tsx
  src/shared/interface/templatesType.ts
  src/utils/constants/buttonPositions.ts
  src/utils/constants/failurePositions.ts
  src/utils/constants/successImages.ts
  src/utils/interface/constants.ts
  tailwind.config.js
  yarn.lock
Labels: ✨FEAT
